// <auto-generated />
namespace Optical_Office_Mangment_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addglassestype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addglassestype));
        
        string IMigrationMetadata.Id
        {
            get { return "202407291147389_add-glasses-type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
