// <auto-generated />
namespace Optical_Office_Mangment_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class removeworkeridfromoptics : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeworkeridfromoptics));
        
        string IMigrationMetadata.Id
        {
            get { return "202407261206506_remove-worker-id-from-optics"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
