// <auto-generated />
namespace Optical_Office_Mangment_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class lastupdateusingfluentapi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lastupdateusingfluentapi));
        
        string IMigrationMetadata.Id
        {
            get { return "202407261317239_last-update-using-fluent-api"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
