// <auto-generated />
using System;
using API_Part_In_Office_Managment_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Part_In_Office_Managment_System.Migrations
{
    [DbContext(typeof(OpticsAPIContext))]
    [Migration("20240808180856_inti")]
    partial class inti
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Part_In_Office_Managment_System.Data.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Report_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Report_id");

                    b.ToTable("Bill");
                });

            modelBuilder.Entity("API_Part_In_Office_Managment_System.Data.DestroyedOptic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Report_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Report_id");

                    b.ToTable("DestroyedOptics");
                });

            modelBuilder.Entity("API_Part_In_Office_Managment_System.Data.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Report_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Report_id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("API_Part_In_Office_Managment_System.Data.Reports", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BillsTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LosesTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<decimal>("PaymentsTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReportTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("API_Part_In_Office_Managment_System.Data.Bill", b =>
                {
                    b.HasOne("API_Part_In_Office_Managment_System.Data.Reports", "report")
                        .WithMany("Bills")
                        .HasForeignKey("Report_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("report");
                });

            modelBuilder.Entity("API_Part_In_Office_Managment_System.Data.DestroyedOptic", b =>
                {
                    b.HasOne("API_Part_In_Office_Managment_System.Data.Reports", "report")
                        .WithMany("DestroyedOptics")
                        .HasForeignKey("Report_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("report");
                });

            modelBuilder.Entity("API_Part_In_Office_Managment_System.Data.Payment", b =>
                {
                    b.HasOne("API_Part_In_Office_Managment_System.Data.Reports", "report")
                        .WithMany("payments")
                        .HasForeignKey("Report_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("report");
                });

            modelBuilder.Entity("API_Part_In_Office_Managment_System.Data.Reports", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("DestroyedOptics");

                    b.Navigation("payments");
                });
#pragma warning restore 612, 618
        }
    }
}
